
pipeline {

    agent {label "ubuntu_interactive" }

    stages {
        stage('Connection test') {
            steps { script {

                print  "I am alive!"

            }}
        }
    }
}
